# image will be published to ghcr.io/<user>/<name>
name: lxqt-ublue
# description will be included in the image's metadata
description: Minimal lxqt ublue-os image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:  
       - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
       - alacritty
       - breeze-cursor-theme
       - breeze-gtk
       - breeze-icon-theme
       - firewall-config
       - fish
       - initial-setup-gui
       - libqtxdg
       - lxqt-about
       - lxqt-archiver
       - lxqt-config
       - lxqt-globalkeys
       - lxqt-notificationd
       - lxqt-openssh-askpass
       - lxqt-panel
       - lxqt-policykit
       - lxqt-powermanagement
       - lxqt-qtplugin
       - lxqt-runner
       - lxqt-session
       - lxqt-themes
       - lxqt-themes-fedora
       - micro
       - network-manager-applet
       - nm-connection-editor
       - notification-daemon
       - obconf
       - pcmanfm-qt
       - perl-File-MimeInfo
       - podman-compose
       - qt5-qtimageformats
       - sddm
       - sddm-themes
       - starship
       - upower
       - xdg-desktop-portal-kde
       - xdg-user-dirs
       - xfwm4
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
       - firefox
       - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
       #- qterminal
       #- openbox

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
         - org.mozilla.firefox
         - org.mozilla.Thunderbird
         - com.github.tchx84.Flatseal
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),

      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        # - org.gnome.eog
        

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
